version: "3.4"
services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME-wishes}_postgres
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
